version: "3.8"

services:
  app:
    image: pushc/devops-for-developers-project-74
    build:
      context: .
      dockerfile: Dockerfile
    container_name: blog_app
    working_dir: /app
    command: make test
